### teste de login
POST http://localhost:40000/Login HTTP/1.1
 content-type: application/json
 //Authorization: Bearer eyJhbGciOiJIUzI
 
 {
 "username": "qwe",
 "password": "qwe"
 }

### teste de logout

POST http://localhost:40000/Logout HTTP/1.1
 content-type: application/json
 //Authorization: Bearer eyJhbGciOiJIUzI1NiI

 {

 } 
